init:
  _target_: models.StaticHierarchicalBERT
  _recursive_: false
embedding: 
  tokenizer: 
  hierarchical: true
  type: static
  kappa: 3
  kappa_trainable: true
  alpha: 20
  alpha_trainable: true
  num_levels: 6
  fully_trainable_scaling: false