test: false

hydra:
  run:
    dir: models/mimic3/plain # output dir
  job:
    chdir: true

defaults:
    - _self_ # important, otherwise keeps params from this config
    - data: synthetic
    - model: static_h_bert
training:
    batch_size: 64
    epochs: 1
    checkpoint_frequency: 1
    optimizer:
        _target_: __main__.optim.Adam
        _recursive_: false
        #lr: 1.e-5
    from_checkpoint: false        
    validation_size: 0.1
    tasks:
        plos_global: false #check whether patient has at least one plos longer than
        plos_threshold: 7

model:
    name: bert
    save_name: test_model
    load_model: false
    architecture:
        hidden_size: 120 # num hidden_size: 192 (for medbert)
        num_hidden_layers: 3 # num_hidden_layers: 6 (for medbert)
        num_attention_heads: 3 # num_attention_heads: 6 (for mdebert)
        intermediate_size: 200 # intermediate_size: 64 ?
        hidden_dropout_prob: 0
data:
    dir: null # raw data directory, if null use data dir inside project
    mask_prob: 0.15
    channels:
        - visits 
        - abs_pos
        - ages
        - values
    tokenizer:
        _target_: __main__.tokenizer.EHRTokenizer
        _recursive_: false
        pad_len: 100
        