training:
    batch_size: 64
    epochs: 1
    checkpoint_frequency: 1
    optimizer:
        _target_: __main__.Adam
        lr: 1.e-5
    from_checkpoint: false        
    validation_size: 0.1
call_model:
    _target_: utils.get_bert_for_pretraining
model:
    _target_: models.StaticHierarchicalEmbedding
    name: bert
    save_name: test_model
    load_model: false
    hidden_size: 192
    num_hidden_layers: 6
    num_attention_heads: 6
    intermediate_size: 64
    hidden_dropout_prob: 0
    validation_size: 0.1
    embedding: 
        hierarchical: true
        type: static
        kappa: 3
        kappa_trainable: true
        alpha: 20
        alpha_trainable: true
        num_levels: 6
        fully_trainable_scaling: false
        
data:
    dir: null
    name: synthetic
    channels: 
        - visits 
        - abs_pos
        - ages
        - values
    mask_prob: 0.15
    pad_len: 300
    plos: false
    