training:
    batch_size: 64
    epochs: 1
    checkpoint_frequency: 1
    optimizer:
        _target_: __main__.optim.Adam
        _recursive_: false
        lr: 1.e-5
    from_checkpoint: false        
    validation_size: 0.1

model:
    init:
        _target_: models.StaticHierarchicalBERT
        _recursive_: false
    name: bert
    save_name: test_model
    load_model: false
    # num hidden_size: 192 (for medbert)
    hidden_size: 100
    # num_hidden_layers: 6 (for medbert)
    num_hidden_layers: 3
    # num_attention_heads: 6 (for mdebert)
    num_attention_heads: 3
    # intermediate_size: 64 ?
    intermediate_size: 200
    hidden_dropout_prob: 0
    validation_size: 0.1
    embedding: 
        hierarchical: true
        type: static
        kappa: 3
        kappa_trainable: true
        alpha: 20
        alpha_trainable: true
        num_levels: 6
        fully_trainable_scaling: false
        
data:
    dir: null
    name: synthetic
    channels: 
        - visits 
        - abs_pos
        - ages
        - values
    mask_prob: 0.15
    pad_len: 100
    plos: false
    