training:
    batch_size: 64
    epochs: 1
    checkpoint_frequency: 1
    optimizer:
        _target_: my_app.AdamH
        lr: 0.00001
    from_checkpoint: false        
    validation_size: 0.1
model:
    name: test_model
    load_model: false
    hidden_size: 192
    num_hidden_layers: 6
    num_attention_heads: 6
    intermediate_size: 64
    hidden_dropout_prob: 0
    validation_size: 0.1
    embedding: 
        kappa: 3
        alpha: 20
data:
    name: synthetic
    embedding_type: static
    channels: 
        - visits 
        - abs_pos
        - ages
        - values
    mask_prob: 0.15
    pad_len: 300
    plos: false